import { Task } from "@/constants/types";

export const TestTasks: Task[] = [
  {
    id: -1,
    title: "Call the dentist",
    estimatedMinutes: 10,
    complexity: "Simple",
    urgent: true,
    completed: false,
    date: "2026-09-17",
  },
  {
    id: -2,
    title: "Reply to emails",
    estimatedMinutes: 15,
    complexity: "Simple",
    urgent: false,
    completed: false,
    date: "2026-09-17",
  },
  {
    id: -3,
    title: "Buy groceries",
    estimatedMinutes: 30,
    complexity: "Simple",
    urgent: false,
    completed: false,
    date: "2026-09-17",
  },
  {
    id: -4,
    title: "Finish project outline",
    estimatedMinutes: 45,
    complexity: "Moderate",
    urgent: false,
    completed: false,
    date: "2026-09-17",
  },
  {
    id: -5,
    title: "Review project requirements",
    estimatedMinutes: 30,
    complexity: "Moderate",
    urgent: false,
    completed: false,
    date: "2026-09-17",
  },
  {
    id: -6,
    title: "Build authentication flow",
    estimatedMinutes: 90,
    complexity: "Complex",
    urgent: false,
    completed: false,
    date: "2026-09-17",
  },
  {
    id: -7,
    title: "Refactor database architecture",
    estimatedMinutes: 120,
    complexity: "Complex",
    urgent: false,
    completed: false,
    date: "2026-09-17",
  },
];
