import { Task } from "@/app/(tabs)/index";

export const TestTasks: Task[] = [
  {
    id: 1,
    title: "Call the dentist",
    estimatedMinutes: 10,
    complexity: "simple",
    urgent: true,
    completed: false,
    date: "2026-08-27",
  },
  {
    id: 2,
    title: "Reply to emails",
    estimatedMinutes: 15,
    complexity: "simple",
    urgent: false,
    completed: false,
    date: "2026-08-27",
  },
  {
    id: 3,
    title: "Buy groceries",
    estimatedMinutes: 30,
    complexity: "simple",
    urgent: false,
    completed: false,
    date: "2026-08-27",
  },
  {
    id: 4,
    title: "Finish project outline",
    estimatedMinutes: 45,
    complexity: "moderate",
    urgent: false,
    completed: false,
    date: "2026-08-27",
  },
  {
    id: 5,
    title: "Review project requirements",
    estimatedMinutes: 30,
    complexity: "moderate",
    urgent: false,
    completed: false,
    date: "2026-08-27",
  },
  {
    id: 6,
    title: "Build authentication flow",
    estimatedMinutes: 90,
    complexity: "complex",
    urgent: false,
    completed: false,
    date: "2026-08-27",
  },
  {
    id: 7,
    title: "Refactor database architecture",
    estimatedMinutes: 120,
    complexity: "complex",
    urgent: false,
    completed: false,
    date: "2026-08-27",
  },
];
